[build]
  base = "client/"

[[redirects]]
  from = "https://setwithfriends.netlify.app/*"
  to = "https://setwithfriends.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
